<li class="your-store-li">
	<a class="your-store drop-show">Select Your Store<i class="fa fa-angle-down"
														aria-hidden="true"></i>
	</a>
	<div class="dropdown-content">
		<ul class="list-unstyled">
			<li>
				<a class="black-small-text" href="/find-your-store/">Find your store</a>
			</li>
			<li>
				<a class="black-small-text" href="/find-store/">Find store</a>
			</li>
		</ul>
	</div>
</li>
<li class="sign-li">
	<a class="drop-show">Sign In Or Register</a><i class="fa fa-angle-down" aria-hidden="true"></i>
	<div class="dropdown-content">
		<ul class="list-unstyled sign">
			<li><a class="black-small-text" href="/customer/account/login/">Sign In</a></li>
			<li><a class="black-small-text" href="/customer/account/create/">Create an Account</a>
			</li>
		</ul>
	</div>
</li>
<li class="dropdown">
	<a class="drop-show">Favorites <i class="fa fa-angle-down" aria-hidden="true"></i></a>
	<div class="dropdown-content">
		<ul class="list-unstyled">
			<li>
				<a class="black-small-text" href="/">Favorite</a>
			</li>
		</ul>
	</div>
</li>