<div class="carousel-home">
	<div class="item">
		<img src="<?php echo $this->getViewFileUrl('images/slides/slide1.png'); ?>" alt=""/>
		<div class="block-position">
			<div class="container">
				<div class="row">
					<div class="col-sm-7">
						<div class="top">
							<div class="row">
								<div class="col-sm-3">
									<div class="white-line"></div>
								</div>
								<div class="col-sm-6">
									<p class="yellow-uppercase-text">Limited Time Offer</p>
								</div>
								<div class="col-sm-3">
									<div class="white-line"></div>
								</div>
							</div>
						</div>
						<p class="text-slide1">two toppings, 10 wings, 2 liter</p>
						<div class="text-slide2">FOR <span class="small">$</span>27.99 only</div>
						<div class="bottom">
							<div class="row">
								<div class="col-sm-3 first">
									<div class="white-line"></div>
								</div>
								<div class="col-sm-6">
									<div class="logo-img-in-slider">
										<img src="<?php echo $this->getViewFileUrl('images/logo-slide.png'); ?>"
											 alt=""/>
									</div>
								</div>
								<div class="col-sm-3 second">
									<div class="white-line"></div>
								</div>
							</div>
						</div>
						<div class="button-block"><a class="green-button w179 button-center">Order now</a></div>
					</div>
				</div>
			</div>
		</div>
	</div>

	<div class="item">
		<img src="<?php echo $this->getViewFileUrl('images/slides/slide1.png'); ?>" alt=""/>
		<div class="block-position">
			<div class="container">
				<div class="row">
					<div class="col-sm-7">
						<div class="top">
							<div class="row">
								<div class="col-sm-3">
									<div class="white-line"></div>
								</div>
								<div class="col-sm-6">
									<p class="yellow-uppercase-text">Limited Time Offer</p>
								</div>
								<div class="col-sm-3">
									<div class="white-line"></div>
								</div>
							</div>
						</div>
						<p class="text-slide1">two toppings, 10 wings, 2 liter</p>
						<div class="text-slide2">FOR <span class="small">$</span>27.99 only</div>
						<div class="bottom">
							<div class="row">
								<div class="col-sm-3 first">
									<div class="white-line"></div>
								</div>
								<div class="col-sm-6">
									<div class="logo-img-in-slider">
										<img src="<?php echo $this->getViewFileUrl('images/logo-slide.png'); ?>"
											 alt=""/>
									</div>
								</div>
								<div class="col-sm-3 second">
									<div class="white-line"></div>
								</div>
							</div>
						</div>
						<div class="button-block"><a class="green-button w179 button-center">Order now</a></div>
					</div>
				</div>
			</div>
		</div>
	</div>

	<div class="item">
		<img src="<?php echo $this->getViewFileUrl('images/slides/slide1.png'); ?>" alt=""/>
		<div class="block-position">
			<div class="container">
				<div class="row">
					<div class="col-sm-7">
						<div class="top">
							<div class="row">
								<div class="col-sm-3">
									<div class="white-line"></div>
								</div>
								<div class="col-sm-6">
									<p class="yellow-uppercase-text">Limited Time Offer</p>
								</div>
								<div class="col-sm-3">
									<div class="white-line"></div>
								</div>
							</div>
						</div>
						<p class="text-slide1">two toppings, 10 wings, 2 liter</p>
						<div class="text-slide2">FOR <span class="small">$</span>27.99 only</div>
						<div class="bottom">
							<div class="row">
								<div class="col-sm-3 first">
									<div class="white-line"></div>
								</div>
								<div class="col-sm-6">
									<div class="logo-img-in-slider">
										<img src="<?php echo $this->getViewFileUrl('images/logo-slide.png'); ?>"
											 alt=""/>
									</div>
								</div>
								<div class="col-sm-3 second">
									<div class="white-line"></div>
								</div>
							</div>
						</div>
						<div class="button-block"><a class="green-button w179 button-center">Order now</a></div>
					</div>
				</div>
			</div>
		</div>
	</div>

</div>
<script type="text/javascript">
	require([
		"jquery"
	], function ($) {
		$(document).ready(function () {

			$('.carousel-home').owlCarousel({
				items: 1,
				itemsTablet: [768, 1],
				itemsDesktopSmall: [979, 1],
				itemsDesktop: [1199, 1],
				pagination: true,
				autoHeight: true
			});
		});
	});


</script>