<?php
// @codingStandardsIgnoreFile

/** @var $block \Magento\Customer\Block\Account\AuthorizationLink */
$dataPostParam = '';
if ($block->isLoggedIn()) {
	$dataPostParam = sprintf(" data-post='%s'", $block->getPostParams());
}
?>
<li class="your-store-li">
	<a href="" class="your-store">Select Your Store<i class="fa fa-angle-down"
													  aria-hidden="true"></i>
	</a>
	<div class="dropdown1">
		<ul class="list-unstyled">
			<li>
				<a class="black-small-text" href="http://purysh.com.ua/find-your-store/">Find your store</a>
			</li>
			<li>
				<a class="black-small-text" href="http://purysh.com.ua/find-store/">Find store</a>
			</li>
		</ul>
	</div>
</li>
<li class="sign-li"><a href="#">Sign In Or Register</a><i class="fa fa-angle-down" aria-hidden="true"></i>
	<div class="dropdown1">
		<ul class="list-unstyled sign">
			<li><a class="black-small-text" href="http://purysh.com.ua/customer/account/login/">Sign In</a></li>
			<li><a class="black-small-text" href="http://purysh.com.ua/customer/account/create/">Create an Account</a>
			</li>
		</ul>
	</div>
</li>
<li><a href="">Favorites<i class="fa fa-angle-down" aria-hidden="true"></i></a>
	<div class="dropdown1">test</div>
</li>
<li class="cart-li">
	<span class="total">$65.85</span><a class="cart-a" href="">
		<i class="fa fa-angle-down"
		   aria-hidden="true"></i></a>
</li>

